import React, { useState } from 'react';
import { 
  Sparkles, 
  MapPin, 
  MessageSquare, 
  Download, 
  Share,
  Crown,
  Loader
} from 'lucide-react';
import { usePaymentContext } from '../hooks/usePaymentContext';

const RemixGenerator = ({ user }) => {
  const [scenario, setScenario] = useState('');
  const [location, setLocation] = useState('');
  const [customPrompt, setCustomPrompt] = useState('');
  const [generatedCard, setGeneratedCard] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [paid, setPaid] = useState(user.subscriptionStatus === 'premium');
  
  const { createSession } = usePaymentContext();

  const scenarios = [
    'Traffic Stop',
    'Police Questioning',
    'Home Search',
    'Public Interaction',
    'Arrest Situation',
    'Border Crossing',
    'Protest Rights',
    'Custom Scenario'
  ];

  const generateCard = async () => {
    if (!paid && user.subscriptionStatus !== 'premium') {
      // Require payment for AI generation
      try {
        await createSession();
        setPaid(true);
      } catch (error) {
        console.error('Payment failed:', error);
        return;
      }
    }

    setIsGenerating(true);
    
    // Simulate AI generation
    setTimeout(() => {
      const card = {
        title: `${scenario} Rights - ${user.selectedState}`,
        scenario: scenario,
        location: location || user.selectedState,
        content: {
          whatToDo: [
            'Remain calm and polite at all times',
            'Keep your hands visible',
            'Clearly state you are exercising your rights',
            'Ask if you are free to leave',
            'Request to speak with an attorney if detained'
          ],
          whatNotToDo: [
            'Do not consent to searches without a warrant',
            'Do not answer questions beyond identification',
            'Do not resist physically, even if you believe the stop is unlawful',
            'Do not argue or become confrontational',
            'Do not provide false information'
          ],
          keyRights: [
            'Right to remain silent (5th Amendment)',
            'Right to refuse consent to searches',
            'Right to record police interactions',
            'Right to an attorney',
            'Right to know the reason for the stop'
          ],
          scripts: [
            '"I am exercising my right to remain silent."',
            '"I do not consent to any searches."',
            '"Am I free to go?"',
            '"I would like to speak to an attorney."'
          ]
        },
        generated: new Date().toLocaleString()
      };
      
      setGeneratedCard(card);
      setIsGenerating(false);
    }, 3000);
  };

  const shareCard = () => {
    if (navigator.share) {
      navigator.share({
        title: generatedCard.title,
        text: `Know your rights: ${generatedCard.title}`,
        url: window.location.href
      });
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(`${generatedCard.title}\n\nGenerated by Zara Rights`);
      alert('Card link copied to clipboard!');
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header */}
      <div className="glass-effect rounded-xl p-6 mb-8">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">
              AI Rights Generator
            </h1>
            <p className="text-white/80">Create personalized rights cards for any situation</p>
          </div>
          
          {!paid && user.subscriptionStatus !== 'premium' && (
            <div className="flex items-center space-x-2 bg-yellow-500/20 border border-yellow-500/30 rounded-lg px-4 py-2">
              <Crown className="h-5 w-5 text-yellow-400" />
              <span className="text-yellow-400 font-medium">Premium Feature</span>
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Generator Form */}
        <div className="space-y-6">
          <div className="glass-effect rounded-xl p-6">
            <h2 className="text-xl font-semibold text-white mb-4">Generate Your Card</h2>
            
            <div className="space-y-4">
              {/* Scenario Selection */}
              <div>
                <label className="block text-white font-medium mb-2">
                  Scenario
                </label>
                <select
                  value={scenario}
                  onChange={(e) => setScenario(e.target.value)}
                  className="w-full bg-white/10 border border-white/20 text-white 
                           rounded-lg px-4 py-3 focus:outline-none focus:ring-2 
                           focus:ring-white/30"
                >
                  <option value="" className="text-gray-900">Select a scenario</option>
                  {scenarios.map((s) => (
                    <option key={s} value={s} className="text-gray-900">{s}</option>
                  ))}
                </select>
              </div>

              {/* Location */}
              <div>
                <label className="block text-white font-medium mb-2">
                  Specific Location (Optional)
                </label>
                <div className="relative">
                  <MapPin className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-white/60" />
                  <input
                    type="text"
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    placeholder={`Default: ${user.selectedState}`}
                    className="w-full bg-white/10 border border-white/20 text-white 
                             rounded-lg pl-10 pr-4 py-3 focus:outline-none focus:ring-2 
                             focus:ring-white/30 placeholder-white/50"
                  />
                </div>
              </div>

              {/* Custom Prompt */}
              <div>
                <label className="block text-white font-medium mb-2">
                  Additional Details (Optional)
                </label>
                <textarea
                  value={customPrompt}
                  onChange={(e) => setCustomPrompt(e.target.value)}
                  placeholder="Describe any specific circumstances or questions..."
                  rows={3}
                  className="w-full bg-white/10 border border-white/20 text-white 
                           rounded-lg px-4 py-3 focus:outline-none focus:ring-2 
                           focus:ring-white/30 placeholder-white/50 resize-none"
                />
              </div>

              {/* Generate Button */}
              <button
                onClick={generateCard}
                disabled={!scenario || isGenerating}
                className="w-full bg-accent hover:bg-accent/90 disabled:bg-white/10 
                         disabled:text-white/50 text-white font-medium py-3 px-4 
                         rounded-lg transition-colors flex items-center justify-center space-x-2"
              >
                {isGenerating ? (
                  <>
                    <Loader className="h-5 w-5 animate-spin" />
                    <span>Generating...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="h-5 w-5" />
                    <span>Generate Rights Card</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Pricing Info */}
          {!paid && user.subscriptionStatus !== 'premium' && (
            <div className="glass-effect rounded-xl p-6">
              <div className="flex items-center space-x-2 mb-4">
                <Crown className="h-6 w-6 text-yellow-400" />
                <h3 className="text-lg font-semibold text-white">Premium Feature</h3>
              </div>
              <p className="text-white/80 mb-4">
                AI-generated rights cards require a micro-transaction of $0.001 per generation.
              </p>
              <div className="text-sm text-white/60">
                <p>• Personalized to your specific situation</p>
                <p>• State-specific legal information</p>
                <p>• Shareable format</p>
                <p>• Available in English and Spanish</p>
              </div>
            </div>
          )}
        </div>

        {/* Generated Card */}
        <div>
          {generatedCard ? (
            <div className="glass-effect rounded-xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold text-white">{generatedCard.title}</h2>
                <div className="flex space-x-2">
                  <button
                    onClick={shareCard}
                    className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors"
                  >
                    <Share className="h-5 w-5 text-white" />
                  </button>
                  <button className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors">
                    <Download className="h-5 w-5 text-white" />
                  </button>
                </div>
              </div>

              <div className="space-y-6">
                {/* What To Do */}
                <div>
                  <h3 className="font-semibold text-white mb-2">✅ What To Do</h3>
                  <ul className="space-y-1">
                    {generatedCard.content.whatToDo.map((item, index) => (
                      <li key={index} className="text-white/90 text-sm">• {item}</li>
                    ))}
                  </ul>
                </div>

                {/* What Not To Do */}
                <div>
                  <h3 className="font-semibold text-white mb-2">❌ What NOT To Do</h3>
                  <ul className="space-y-1">
                    {generatedCard.content.whatNotToDo.map((item, index) => (
                      <li key={index} className="text-white/90 text-sm">• {item}</li>
                    ))}
                  </ul>
                </div>

                {/* Key Rights */}
                <div>
                  <h3 className="font-semibold text-white mb-2">⚖️ Your Rights</h3>
                  <ul className="space-y-1">
                    {generatedCard.content.keyRights.map((right, index) => (
                      <li key={index} className="text-white/90 text-sm">• {right}</li>
                    ))}
                  </ul>
                </div>

                {/* Scripts */}
                <div>
                  <h3 className="font-semibold text-white mb-2">💬 What To Say</h3>
                  <div className="space-y-2">
                    {generatedCard.content.scripts.map((script, index) => (
                      <div key={index} className="bg-white/10 rounded p-2">
                        <p className="text-white/90 text-sm">{script}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="text-center text-white/60 text-xs">
                  Generated on {generatedCard.generated}
                </div>
              </div>
            </div>
          ) : (
            <div className="glass-effect rounded-xl p-6 text-center">
              <Sparkles className="h-12 w-12 text-white/50 mx-auto mb-4" />
              <p className="text-white/70">
                Select a scenario and generate your personalized rights card
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default RemixGenerator;